server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redbook?useSSL=false&serverTimezone=UTC
    username: root
    password: ljb112233
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  graphql:
    graphiql:
      enabled: true